/* =========================================================
   YOUNG WAVE CREATIVE — i18n + influencer dataset
   Languages: ko, en, vi, th, id, zh
   ========================================================= */

/* ---------- Category & country labels ---------- */
const LABELS = {
  country: {
    vietnam:    {ko:"베트남", en:"Vietnam", vi:"Việt Nam", th:"เวียดนาม", id:"Vietnam", zh:"越南"},
    philippines:{ko:"필리핀", en:"Philippines", vi:"Philippines", th:"ฟิลิปปินส์", id:"Filipina", zh:"菲律宾"},
    thailand:   {ko:"태국", en:"Thailand", vi:"Thái Lan", th:"ไทย", id:"Thailand", zh:"泰国"}
  },
  cat: {
    beauty:      {ko:"뷰티", en:"Beauty", vi:"Làm đẹp", th:"ความงาม", id:"Kecantikan", zh:"美妆"},
    livecommerce:{ko:"라이브커머스", en:"Live Commerce", vi:"Live Commerce", th:"ไลฟ์คอมเมิร์ซ", id:"Live Commerce", zh:"直播电商"},
    fashion:     {ko:"패션", en:"Fashion", vi:"Thời trang", th:"แฟชั่น", id:"Fashion", zh:"时尚"},
    music:       {ko:"음악", en:"Music", vi:"Âm nhạc", th:"ดนตรี", id:"Musik", zh:"音乐"},
    gaming:      {ko:"게임/스트리밍", en:"Gaming / Streaming", vi:"Game / Stream", th:"เกม / สตรีม", id:"Game / Streaming", zh:"游戏/直播"},
    couple:      {ko:"커플 크리에이터", en:"Couple Creator", vi:"Cặp đôi", th:"คู่รัก", id:"Pasangan", zh:"情侣博主"},
    celebrity:   {ko:"셀럽", en:"Celebrity", vi:"Người nổi tiếng", th:"คนดัง", id:"Selebriti", zh:"明星"},
    genz:        {ko:"Gen Z", en:"Gen Z", vi:"Gen Z", th:"Gen Z", id:"Gen Z", zh:"Z世代"}
  }
};

/* ---------- Influencer dataset ---------- */
const INFLUENCERS = [
  {name:"Call Me Duy", real:"Vũ Duy · 1997", country:"vietnam", cats:["livecommerce","beauty"],
   followers:"1.2M", fnote:"TikTok",
   plat:[{t:"tiktok",u:"https://www.tiktok.com/@justvuduy16"}],
   ko:"베트남 남성 뷰티 No.1 블로거이자 틱톡 최상위 라이브커머스 스트리머. 성분 분석 기반 리뷰로 신뢰도가 높고, 2022 KOC Vietnam 시즌1 우승자.",
   en:"Vietnam's No.1 male beauty creator and a top-tier TikTok live-commerce streamer. Science-based reviews; winner of KOC Vietnam Season 1 (2022)."},
  {name:"H&M Channel", real:"Lê Hùng & Bạch My", country:"vietnam", cats:["couple","fashion"],
   followers:"3.5M", fnote:"YouTube",
   plat:[{t:"youtube",u:"https://www.youtube.com/@HMChannel12"}],
   ko:"약 350만 구독 베트남 초대형 커플 크리에이터. 예능형 리얼리티·일상·먹방·여행 콘텐츠로 MZ에 강한 영향력. 자체 패션 브랜드 런칭.",
   en:"3.5M-subscriber mega couple creator. Reality, daily-life, mukbang and travel content with huge MZ reach; launched their own fashion brand."},
  {name:"Lép The Little Kid", real:"Huỳnh Quang Minh", country:"vietnam", cats:["genz","fashion"],
   followers:"860K", fnote:"TikTok",
   plat:[{t:"tiktok",u:"https://www.tiktok.com/@lepthelittlekid"}],
   ko:"유머 + 남성 자기계발·연애·심리 콘텐츠. 2개월 만에 40만 팔로워 달성한 급성장 KOL로 틱톡숍 남성 충성 구매층이 두텁다.",
   en:"Humor plus male self-development content. Fast-rising KOL (400K in 2 months) with a loyal male buyer base on TikTok Shop."},
  {name:"Trinh Phạm", real:"1991", country:"vietnam", cats:["beauty"],
   followers:"1.2M", fnote:"YouTube",
   plat:[{t:"youtube",u:"https://www.youtube.com/@trinhpham91"}],
   ko:"베트남 대표 주부 뷰티 크리에이터. 2014년부터 스킨케어·뷰티 콘텐츠로 활동, 젊은 여성·주부층에 막강한 영향력.",
   en:"Leading 'mom' beauty creator. Skincare & beauty content since 2014; powerful influence among young women and young mothers."},
  {name:"Góc của Rư", real:"Bùi Xuân Thảo · 1989", country:"vietnam", cats:["beauty"],
   followers:"970K", fnote:"TikTok",
   plat:[{t:"tiktok",u:"https://www.tiktok.com/@goc.cua.ru"}],
   ko:"메이크업·스킨케어·자기계발 콘텐츠로 베트남 뷰티 커뮤니티의 영향력자. TikTok 97만 / YouTube 71만.",
   en:"Makeup, skincare and self-growth content; an influencer in Vietnam's beauty community. TikTok 970K / YouTube 710K."},
  {name:"Suni Hạ Linh", real:"Ngô Đặng Thu Giang", country:"vietnam", cats:["celebrity","music"],
   followers:"1.08M", fnote:"Facebook",
   plat:[{t:"facebook",u:"https://www.facebook.com/suniofficial0609/"}],
   ko:"가수·배우 셀럽 인플루언서. 한국 FNC 연습생 경험·한국어 구사·K-pop 친화 이미지로 한-베 행사·K브랜드 마케팅 단골. 前 라네즈 베트남 모델.",
   en:"Singer-actress celebrity. Ex-FNC trainee, Korean-speaking, K-pop-friendly image — a go-to for Korea–Vietnam events and K-brands. Former Laneige VN model."},
  {name:"MLee", real:"Quách Tapiau Maily · 1992", country:"vietnam", cats:["celebrity","fashion"],
   followers:"920K", fnote:"Instagram",
   plat:[{t:"instagram",u:"https://www.instagram.com/mleetapiau/"}],
   ko:"베트남·프랑스 혼혈 가수·래퍼·배우·MC. 'Chị Đẹp' 출연, Miss Universe Vietnam 2024 Top5. 셀럽 + 패션 아이콘 포지션.",
   en:"Vietnamese-French singer, rapper, actress and MC. 'Chị Đẹp' cast, Miss Universe Vietnam 2024 Top 5. Celebrity + fashion-icon positioning."},
  {name:"Trương Thanh Trúc", real:"Fashion Editor", country:"vietnam", cats:["fashion","beauty"],
   followers:"30K", fnote:"Instagram",
   plat:[{t:"instagram",u:"https://www.instagram.com/thanhtructruong/"}],
   ko:"베트남 1세대 패션모델·스타일리스트·패션 에디터. 설화수·라메르·랑콤·시세이도 등 럭셔리 브랜드 초청 인플루언서로 30-40대 상류층 타깃에 최적.",
   en:"First-gen fashion model, stylist and editor. Invited by Sulwhasoo, La Mer, Lancôme, Shiseido — ideal for upscale 30–40s luxury targeting."},
  {name:"Huong Pham", real:"Phạm Hương · 1991", country:"vietnam", cats:["celebrity","beauty"],
   followers:"900K", fnote:"Instagram",
   plat:[{t:"instagram",u:"https://www.instagram.com/phamhuongbee/"}],
   ko:"미스 유니버스 베트남 2015 우승, 세계대회 Top5. '국민 미인' 신드롬. 현재 럭셔리 라이프로 다시 주목 — VVIP 뷰티·패션·육아 브랜딩 최적.",
   en:"Miss Universe Vietnam 2015 winner, global Top 5 — a national icon. Now a luxury-lifestyle figure; ideal for VVIP beauty, fashion and parenting branding."},
  {name:"KHÁNH", real:"Nguyễn Bảo Khánh · 1999", country:"vietnam", cats:["music","fashion"],
   followers:"3.4M", fnote:"TikTok",
   plat:[{t:"tiktok",u:"https://www.tiktok.com/@khanh.keymusic"}],
   ko:"베트남 인기 DJ·프로듀서. 'Sóng Gió' 등 수억 뷰 히트로 V-pop 신드롬. Z세대가 사랑하는 EDM DJ로 무대 패션·액세서리에 강점.",
   en:"Top DJ-producer behind hundred-million-view hits ('Sóng Gió'). A Gen-Z-loved EDM artist — strong for stage fashion and accessories."},
  {name:"CONG B", real:"Nguyễn Thành Công · 2000", country:"vietnam", cats:["celebrity","beauty"],
   followers:"370K", fnote:"Instagram",
   plat:[{t:"instagram",u:"https://www.instagram.com/kopsskops/"}],
   ko:"Mnet 'Boys Planet' 베트남 대표 출연 아이돌. '비주얼 센터'로 불리며 퓨어·청량 이미지로 뷰티 브랜드 모델로 활약 중인 슈퍼 루키.",
   en:"Idol who represented Vietnam on Mnet's 'Boys Planet'. A 'visual center' super-rookie with a fresh, clean image, active as a beauty-brand model."},
  {name:"Thoại Nghi", real:"Nguyễn Vũ Thoại Nghi · 2005", country:"vietnam", cats:["music","genz","beauty"],
   followers:"600K", fnote:"Facebook",
   plat:[{t:"facebook",u:"https://www.facebook.com/NguyenThoaiNghi140905/"}],
   ko:"Gen Z 여성 솔로 가수·모델. 유럽 EDM 페스티벌 무대에 선 드문 V-pop 신인으로 언론 주목. Gen Z 뷰티·메이크업 관심도 높음.",
   en:"Gen Z female soloist and model — a rare V-pop newcomer on European EDM festival stages. High Gen-Z beauty and makeup affinity."},
  {name:"ViruSs", real:"Đặng Tiến Hoàng · 1988", country:"vietnam", cats:["gaming","music"],
   followers:"3.61M", fnote:"Facebook",
   plat:[{t:"facebook",u:"https://www.facebook.com/ViruSsOP/"}],
   ko:"베트남 '스트리머 4대 천왕'. 유튜버·게임 스트리머·프로듀서. 'Thằng điên' MV 2.6억 뷰. 넥슨 등 한국 게임 현지 마케팅 협업, 남성 팬덤 충성도 최상.",
   en:"One of Vietnam's 'big four' streamers — YouTuber, game streamer and producer ('Thằng điên' MV 260M views). Worked with Korean games (Nexon); top male-fan loyalty."},
  {name:"Ngân Sát Thủ", real:"Ngân Huỳnh · 1994", country:"vietnam", cats:["gaming","fashion"],
   followers:"1.77M", fnote:"Facebook",
   plat:[{t:"facebook",u:"https://www.facebook.com/NST2905/"}],
   ko:"베트남 대표 여성 PUBG Mobile 스트리머. 아이돌급 외모·패션으로 Z세대 인기. 결혼·출산 후에도 뷰티·패션 관심도 상승, 팬덤·인지도형 인플루언서.",
   en:"Vietnam's leading female PUBG Mobile streamer. Idol-like looks and style; strong Gen-Z appeal and a fandom-driven beauty/fashion influencer."},
  {name:"Nabee", real:"Nguyễn Thị Kim Ngân · 1997", country:"vietnam", cats:["gaming","genz"],
   followers:"1.67M", fnote:"YouTube",
   plat:[{t:"youtube",u:"https://www.youtube.com/@NabeeST"}],
   ko:"게임·라이브 스트리밍 메가 크리에이터. 게임 채널 167만 / 브이로그 131만. 귀여운 이미지로 여성 팬층이 두터워 Z세대 타깃 제품에 적합.",
   en:"Gaming and live-streaming mega creator (gaming 1.67M / vlog 1.31M). A cute image with a strong female fanbase — great for Gen-Z products."},
  {name:"Ohsusu", real:"Ngô Quý · 1993", country:"vietnam", cats:["gaming"],
   followers:"2.3M", fnote:"YouTube",
   plat:[{t:"youtube",u:"https://www.youtube.com/OhsusuTV"}],
   ko:"유명 유튜버·전직 프로게이머·스트리머. 게임 플레이·브이로그·음악 커버 등으로 큰 인기, 뷰티·패션 반응도 양호.",
   en:"Popular YouTuber, ex-pro gamer and streamer. Gameplay, vlogs and music covers with wide appeal; solid beauty and fashion response."},
  {name:"Reneé Dominique", real:"Singer-songwriter", country:"philippines", cats:["music","beauty"],
   followers:"1.57M", fnote:"YouTube",
   plat:[{t:"youtube",u:"https://www.youtube.com/channel/UC-fn57_xqMv-PaMmpm-ZspQ"}],
   ko:"필리핀 싱어송라이터·유튜버. 우쿨렐레 감성 팝, Jason Mraz 협업. '뮤직 아티스트 + 내추럴 뷰티 아이콘' 스타일.",
   en:"Filipino singer-songwriter and YouTuber. Ukulele-driven emotive pop, collab with Jason Mraz. A 'music artist + natural beauty icon' style."},
  {name:"Kyo & Luigi", real:"Kyo Quijano & Luigi Pacheco", country:"philippines", cats:["couple","fashion"],
   followers:"1.87M", fnote:"YouTube",
   plat:[{t:"youtube",u:"https://www.youtube.com/kyoquijano"}],
   ko:"필리핀 유튜버·배우·댄서 커플. 댄스·코미디·드라마 출연. 자유분방·유쾌함과 준수한 외모로 젊은 세대 패션 관심 집중.",
   en:"Filipino YouTuber-actor-dancer couple. Dance, comedy and drama work; free-spirited charm and strong fashion appeal to younger audiences."},
  {name:"Baninay & Bryan", real:"Baninay Bautista & Bryan Oropel", country:"philippines", cats:["couple","beauty"],
   followers:"1.83M+1.79M", fnote:"YouTube",
   plat:[{t:"youtube",u:"https://www.youtube.com/c/BaninayBautista"},{t:"youtube",u:"https://www.youtube.com/@BontBryanOropel"}],
   ko:"필리핀 대형 라이프스타일 커플 유튜버(183만+179만). '옆집 언니/다정한 남성' 현실형 매력으로 브랜드가 가장 팔기 쉬운 뷰티 아이콘.",
   en:"Major Filipino lifestyle couple (1.83M + 1.79M). Relatable 'girl/boy next door' charm — the easiest-to-sell, realistic beauty icons for brands."},
  {name:"Jannine Weigel", real:"German-Thai · 2000", country:"thailand", cats:["celebrity","music","beauty"],
   followers:"4.04M", fnote:"YouTube",
   plat:[{t:"youtube",u:"https://www.youtube.com/channel/UChFzJ0bYwztKa4H4oF8fOvw"}],
   ko:"태국 대표 싱어송라이터·배우·유튜버, A-POP 세대 글로벌 스타. 동남아+유럽 혼혈 균형형 얼굴로 K-뷰티·글로벌 화장품 모두 어울리는 진화형 모델.",
   en:"Thailand's leading singer-songwriter, actress and YouTuber; an A-POP global star. A balanced SEA-European look that fits both K-beauty and global brands."}
];

/* ---------- UI translations ---------- */
const I18N = {
  ko:{
    "nav.home":"홈","nav.influencers":"인플루언서","nav.services":"서비스","nav.about":"회사소개","nav.contact":"문의하기",
    "cta.brand":"브랜드 제휴 문의","cta.explore":"인플루언서 풀 보기",
    "hero.badge":"한국 × 동남아 인플루언서 마케팅",
    "hero.title1":"유럽·동남아 특화 인플루언서 커머스","hero.title2":"풀스택 컴퍼니",
    "hero.lead":"광고를 파는 회사가 아닙니다. 셀럽과 인플루언서 풀로 브랜드의 동남아, 유럽 \u0027매출\u0027을 만듭니다. 흩어져 있던 해외 판매 전 과정을 하나의 파이프라인으로 — 과정은 단순하게, 결과는 매출로.",
    "marquee":"인플루언서 → 콘텐츠 제작 → 라이브커머스 → 쇼핑몰 판매 → 매출 정산 · 화장품 인증(DAV·VFA) · 통관·3PL 물류 · 현지 팝업",
    "stats.title":"숫자가 증명합니다","stats.sub":"동남아 전역을 커버하는 실전 네트워크",
    "stat.reach":"누적 인플루언서 도달","stat.countries":"커버 국가 (아세안)","stat.years":"베트남 현지 운영","stat.team":"베트남·한국 임직원",
    "home.svc.title":"하나의 파트너, 끝까지","home.svc.sub":"브랜드 소싱부터 현지 판매·정산까지, 한 팀이 끝까지 책임집니다.",
    "home.why.title":"왜 동남아·유럽, 왜 지금인가","home.why.sub":"베트남 1억 인구의 60%가 35세 미만. 한류 우호 이미지가 지배적인 MZ 소비시장.",
    "why.1.t":"젊은 소비 시장","why.1.d":"베트남 인구의 60%가 35세 미만. 모바일·이커머스 성장세가 가파른 라이징 마켓.",
    "why.2.t":"한류 프리미엄","why.2.d":"K-컬처에 대한 우호적 이미지가 MZ 소비층에 지배적이어서 한국 브랜드 진입에 유리.",
    "why.3.t":"검증된 현지력","why.3.d":"정부·대기업 행사부터 한-베 웹드라마까지, 현지 실행을 직접 운영해 온 트랙레코드.",
    "home.infl.title":"지금, 협업 가능한 인플루언서","home.infl.sub":"방대한 풀의 일부입니다. 카테고리·국가별로 큐레이션했습니다.",
    "home.partner.title":"관계사 & 파트너 네트워크","home.partner.sub":"베트남 최대 MCN부터 미스 유니버스 라이선스까지.",
    "partners.metub":"베트남 최대 MCN","partners.uni":"미스 유니버스 베트남","partners.choo":"통합 마케팅·이벤트","partners.zorba":"칸 수상 프로덕션",
    "cta.title":"동남아·유럽 매출, 지금 만들 차례입니다","cta.sub":"브랜드만 알려주세요. 진입 전략부터 매출까지, 맞춤 제안서로 답하겠습니다.","cta.btn":"무료 제안서 받기",
    "infl.title":"인플루언서 풀","infl.sub":"베트남·필리핀·태국의 검증된 셀럽과 크리에이터. 국가와 카테고리로 필터링하세요.",
    "filter.all":"전체","infl.count":"명의 인플루언서","followers":"팔로워","infl.empty":"해당 조건의 인플루언서가 없습니다.",
    "svc.title":"서비스","svc.sub":"콘텐츠로 알리고, 커머스로 팔고, 인증으로 합법화합니다.",
    "svc.a.t":"라이브커머스 & V-커머스","svc.a.d":"탑티어 라이브 스트리머가 진행하는 실시간 판매 방송으로 즉각적인 전환을 만듭니다.",
    "svc.a.1":"틱톡·페이스북 라이브 커머스","svc.a.2":"인플루언서 실시간 딜·프로모션","svc.a.3":"판매 데이터·리포트 제공",
    "svc.b.t":"공동구매 & 쇼핑몰 운영","svc.b.d":"인플루언서 팬덤 기반 공동구매와 현지 쇼핑몰 운영으로 지속 매출을 만듭니다.","svc.b.1":"인플루언서 공동구매 기획","svc.b.2":"현지 이커머스 입점·운영","svc.b.3":"CS·물류·정산 대행",
    "svc.c.t":"현지 팝업 & 오프라인","svc.c.d":"O2O 전략으로 체험형 팝업과 행사로 브랜드 신뢰와 인지도를 동시에 확보합니다.","svc.c.1":"현지 팝업스토어 기획·운영","svc.c.2":"셀럽 초청·런칭 이벤트","svc.c.3":"정부·대기업 행사 운영",
    "svc.d.t":"콘텐츠 & 캠페인","svc.d.d":"광고 같지 않은 고품질 콘텐츠로 브랜드를 자연스럽게 녹여 인지도를 끌어올립니다.","svc.d.1":"웹드라마·뮤직비디오 PPL","svc.d.2":"숏폼·SNS 캠페인","svc.d.3":"언론 PR·매거진 화보",
    "svc.e.t":"베트남 인증 (화장품·식품)","svc.e.d":"영웨이브 베트남 법인이 직접 화장품 신고(DAV)·식품 등록(VFA)을 진행해 합법 판매를 보장합니다.","svc.e.1":"화장품 신고 — 보건부 DAV","svc.e.2":"식품 안전 등록 — VFA","svc.e.3":"수입·통관·라벨링 대행",
    "svc.f.t":"브랜드 소싱 (한국 지사)","svc.f.d":"Brooks Global이 한국 지사로서 브랜드·광고주 소싱과 커뮤니케이션을 전담합니다.","svc.f.1":"한국 브랜드 소싱·계약","svc.f.2":"캠페인 기획·매니지먼트","svc.f.3":"리포팅·정산 커뮤니케이션",
    "about.title":"회사 소개","about.sub":"아세안의 역동적 에너지를, 한국 브랜드의 매출로 바꾸는 커머스 파트너.",
    "about.story.t":"WE MAKE COOL STUFF FOR YOUR BRAND","about.story.d":"Young Wave Creative는 베트남 호치민을 거점으로 아세안 전역의 프로젝트를 이끌어 왔습니다. 동남아 주요 셀럽·인플루언서와의 협업을 중심으로, 한국의 문화·제품·관광 자원을 결합해 한국 브랜드를 성공적으로 알려왔습니다. 콘텐츠 기획·제작부터 V-커머스, 현지 세일즈까지 — 아세안과 한국을 잇는 강력한 다리가 되겠습니다.",
    "about.fact.name":"회사명","about.fact.ceo":"대표","about.fact.found":"설립","about.fact.hq":"본사","about.fact.team":"임직원","about.fact.biz":"주사업",
    "about.found.v":"2016년 호치민 본사 설립","about.team.v":"베트남 본사 16명 · 한국 지사 3명","about.biz.v":"콘텐츠 제작 · MCN/인플루언서 마케팅 · 광고대행 · V-커머스 · 아세안 통합 마케팅",
    "about.tl.title":"대표 프로젝트","about.ceo.title":"리더십","ceo.role":"대표 / 주한 베트남국가관광청 대표부 기획국장",
    "ceo.c1":"주한 베트남 관광대사 (2017–2029 임기)","ceo.c2":"베트남 조국전선위원회 '민족대단결' 훈장 수훈","ceo.c3":"한국 문화체육관광부 장관 표창","ceo.c4":"한국 정부·대기업 행사를 베트남 현지에서 다수 총괄",
    "about.rel.title":"관계사 네트워크",
    "contact.title":"제휴 문의","contact.sub":"브랜드 정보를 남겨주세요. 영업일 2일 내 맞춤 제안서로 답하겠습니다.",
    "f.name":"담당자명","f.company":"회사/브랜드명","f.email":"이메일","f.cat":"제품 카테고리","f.country":"타깃 국가","f.msg":"문의 내용","f.send":"문의 보내기",
    "f.cat.ph":"선택하세요","f.cat.cosmetic":"화장품","f.cat.food":"식품","f.cat.living":"생활용품","f.cat.game":"모바일 게임","f.cat.device":"전자기기","f.cat.etc":"기타",
    "f.note":"제출 시 담당자 이메일 클라이언트로 내용이 전달됩니다.",
    "contact.office":"베트남 오피스","contact.kr":"한국 (Brooks Global)","contact.email":"이메일",
    "foot.tag":"한국과 동남아·유럽을 잇는 인플루언서 커머스 풀스택 파트너.","foot.menu":"메뉴","foot.contact":"연락처","foot.partner":"한국 지사 파트너","foot.rights":"All rights reserved."
  },
  en:{
    "nav.home":"Home","nav.influencers":"Influencers","nav.services":"Services","nav.about":"About","nav.contact":"Contact",
    "cta.brand":"Brand Inquiry","cta.explore":"Explore the Pool",
    "hero.badge":"Korea × Southeast Asia Influencer Marketing",
    "hero.title1":"Europe & SEA Influencer-Commerce","hero.title2":"Full-Stack Company",
    "hero.lead":"We don't sell ads. With celebrities plus an influencer pool, we build your Southeast Asia & Europe revenue. Complex cross-border sales steps, unified into one pipeline — easy, all the way to revenue.",
    "marquee":"Influencer → Content → Live Commerce → Mall Sales → Settlement · Cosmetic Certification (DAV·VFA) · Customs & 3PL · Local Pop-ups",
    "stats.title":"Young Wave by the numbers","stats.sub":"A battle-tested network covering the region",
    "stat.reach":"Combined influencer reach","stat.countries":"ASEAN countries covered","stat.years":"Years on the ground in Vietnam","stat.team":"Team in Vietnam & Korea",
    "home.svc.title":"One partner, end to end","home.svc.sub":"From ad sourcing to closing local sales—handled full-stack.",
    "home.why.title":"Why Southeast Asia & Europe, why now","home.why.sub":"60% of Vietnam's 100M people are under 35, in a market that loves Korean culture.",
    "why.1.t":"A young consumer market","why.1.d":"60% of Vietnam's population is under 35—a rising market with steep mobile and e-commerce growth.",
    "why.2.t":"The Hallyu premium","why.2.d":"A favorable image of K-culture dominates the MZ consumer base, easing entry for Korean brands.",
    "why.3.t":"Proven local execution","why.3.d":"A track record running everything from government and enterprise events to Korea–Vietnam web dramas.",
    "home.infl.title":"Creators ready to collaborate","home.infl.sub":"A glimpse of a pool curated by category and country.",
    "home.partner.title":"Affiliates & partner network","home.partner.sub":"From Vietnam's largest MCN to the Miss Universe license.",
    "partners.metub":"Vietnam's largest MCN","partners.uni":"Miss Universe Vietnam","partners.choo":"Integrated marketing & events","partners.zorba":"Cannes-awarded production",
    "cta.title":"Time to build your Southeast Asia & Europe revenue","cta.sub":"Just tell us your brand. We'll answer with a tailored go-to-market-to-revenue proposal.","cta.btn":"Get a free proposal",
    "infl.title":"Influencer Pool","infl.sub":"Vetted celebrities and creators across Vietnam, the Philippines and Thailand. Filter by country and category.",
    "filter.all":"All","infl.count":"influencers","followers":"followers","infl.empty":"No influencers match this filter.",
    "svc.title":"Services","svc.sub":"Reach with content, sell with commerce, legalize with certification.",
    "svc.a.t":"Live & V-Commerce","svc.a.d":"Real-time selling streams hosted by top-tier live streamers that drive instant conversion.","svc.a.1":"TikTok & Facebook live commerce","svc.a.2":"Influencer live deals & promos","svc.a.3":"Sales data & reporting",
    "svc.b.t":"Group Buy & Mall Ops","svc.b.d":"Fandom-driven group buys and local mall operations that build recurring revenue.","svc.b.1":"Influencer group-buy planning","svc.b.2":"Local e-commerce listing & ops","svc.b.3":"CS, logistics & settlement",
    "svc.c.t":"Pop-ups & Offline","svc.c.d":"An O2O strategy using experiential pop-ups and events to build trust and awareness at once.","svc.c.1":"Local pop-up planning & ops","svc.c.2":"Celebrity launch events","svc.c.3":"Government & enterprise events",
    "svc.d.t":"Content & Campaigns","svc.d.d":"High-quality content that doesn't feel like an ad, weaving the brand in naturally.","svc.d.1":"Web-drama & MV product placement","svc.d.2":"Short-form & social campaigns","svc.d.3":"Press PR & magazine features",
    "svc.e.t":"Vietnam Certification","svc.e.d":"Our Vietnam entity files cosmetic notifications (DAV) and food registrations (VFA) directly for legal sales.","svc.e.1":"Cosmetic notification — MoH DAV","svc.e.2":"Food safety registration — VFA","svc.e.3":"Import, customs & labeling",
    "svc.f.t":"Brand Sourcing (Korea)","svc.f.d":"Brooks Global, our Korea branch, leads brand/advertiser sourcing and communication.","svc.f.1":"Korean brand sourcing & contracts","svc.f.2":"Campaign planning & management","svc.f.3":"Reporting & settlement comms",
    "about.title":"About Us","about.sub":"A digital marketing company linking ASEAN's dynamic energy with Korea.",
    "about.story.t":"WE MAKE COOL STUFF FOR YOUR BRAND","about.story.d":"Based in Ho Chi Minh City, Young Wave Creative has led projects across ASEAN. Centered on collaboration with the region's top celebrities and influencers, we've successfully promoted Korean culture, products and tourism. From content to V-commerce and local sales, we aim to be a powerful bridge between ASEAN and Korea.",
    "about.fact.name":"Company","about.fact.ceo":"CEO","about.fact.found":"Founded","about.fact.hq":"HQ","about.fact.team":"Team","about.fact.biz":"Business",
    "about.found.v":"Founded in Ho Chi Minh City, 2016","about.team.v":"16 in Vietnam HQ · 3 in Korea branch","about.biz.v":"Content · MCN/influencer marketing · advertising · V-commerce · ASEAN integrated marketing",
    "about.tl.title":"Flagship Projects","about.ceo.title":"Leadership","ceo.role":"CEO / Planning Director, Vietnam National Tourism Office in Korea",
    "ceo.c1":"Vietnam Tourism Ambassador to Korea (2017–2029)","ceo.c2":"'Great Unity' medal, Vietnam Fatherland Front","ceo.c3":"Commendation from Korea's Minister of Culture, Sports & Tourism","ceo.c4":"Directed numerous Korean government & enterprise events in Vietnam",
    "about.rel.title":"Affiliate Network",
    "contact.title":"Partnership Inquiry","contact.sub":"Leave your brand details and we'll send a tailored proposal within 2 business days.",
    "f.name":"Your name","f.company":"Company / brand","f.email":"Email","f.cat":"Product category","f.country":"Target country","f.msg":"Message","f.send":"Send inquiry",
    "f.cat.ph":"Select","f.cat.cosmetic":"Cosmetics","f.cat.food":"Food","f.cat.living":"Household goods","f.cat.game":"Mobile games","f.cat.device":"Electronics","f.cat.etc":"Other",
    "f.note":"Submitting opens your email client with the message pre-filled.",
    "contact.office":"Vietnam Office","contact.kr":"Korea (Brooks Global)","contact.email":"Email",
    "foot.tag":"Your influencer-commerce full-stack partner linking Korea, Southeast Asia & Europe.","foot.menu":"Menu","foot.contact":"Contact","foot.partner":"Korea Branch Partner","foot.rights":"All rights reserved."
  },
  vi:{
    "nav.home":"Trang chủ","nav.influencers":"Influencer","nav.services":"Dịch vụ","nav.about":"Giới thiệu","nav.contact":"Liên hệ",
    "cta.brand":"Hợp tác thương hiệu","cta.explore":"Xem danh sách",
    "hero.badge":"Marketing Influencer Hàn Quốc × Đông Nam Á",
    "hero.title1":"Influencer-Commerce Âu · Đông Nam Á","hero.title2":"Công ty Full-Stack",
    "hero.lead":"Chúng tôi không bán quảng cáo. Với celeb + pool influencer, chúng tôi tạo ra doanh số Đông Nam Á & châu Âu cho thương hiệu. Các bước bán hàng xuyên biên giới phức tạp được gộp vào một pipeline — nhẹ nhàng, đến tận doanh thu.",
    "marquee":"Influencer → Nội dung → Live Commerce → Bán mall → Quyết toán · Chứng nhận mỹ phẩm (DAV·VFA) · Hải quan & 3PL · Pop-up",
    "stats.title":"Young Wave qua những con số","stats.sub":"Mạng lưới thực chiến phủ toàn khu vực",
    "stat.reach":"Tổng lượng tiếp cận","stat.countries":"Quốc gia ASEAN","stat.years":"Năm vận hành tại Việt Nam","stat.team":"Nhân sự VN & Hàn",
    "home.svc.title":"Một đối tác, trọn vẹn","home.svc.sub":"Từ tìm kiếm quảng cáo đến chốt doanh số bản địa — trọn gói.",
    "home.why.title":"Vì sao Đông Nam Á & châu Âu, vì sao bây giờ","home.why.sub":"60% trong 100 triệu dân Việt Nam dưới 35 tuổi, yêu mến văn hóa Hàn.",
    "why.1.t":"Thị trường tiêu dùng trẻ","why.1.d":"60% dân số Việt Nam dưới 35 tuổi — thị trường tăng trưởng mạnh về di động và TMĐT.",
    "why.2.t":"Lợi thế Hallyu","why.2.d":"Hình ảnh tích cực của văn hóa Hàn chiếm ưu thế trong người tiêu dùng trẻ.",
    "why.3.t":"Năng lực bản địa","why.3.d":"Kinh nghiệm vận hành từ sự kiện chính phủ, doanh nghiệp đến web-drama Hàn–Việt.",
    "home.infl.title":"Creator sẵn sàng hợp tác","home.infl.sub":"Một phần của pool được tuyển chọn theo lĩnh vực và quốc gia.",
    "home.partner.title":"Công ty liên kết & đối tác","home.partner.sub":"Từ MCN lớn nhất Việt Nam đến bản quyền Miss Universe.",
    "partners.metub":"MCN lớn nhất Việt Nam","partners.uni":"Miss Universe Việt Nam","partners.choo":"Marketing & sự kiện","partners.zorba":"Production đoạt giải Cannes",
    "cta.title":"Bắt đầu thâm nhập Đông Nam Á & châu Âu ngay","cta.sub":"Cho chúng tôi biết về thương hiệu của bạn, chúng tôi sẽ đề xuất chiến lược phù hợp.","cta.btn":"Yêu cầu tư vấn",
    "infl.title":"Danh sách Influencer","infl.sub":"Người nổi tiếng và creator được tuyển chọn tại Việt Nam, Philippines, Thái Lan. Lọc theo quốc gia và lĩnh vực.",
    "filter.all":"Tất cả","infl.count":"influencer","followers":"người theo dõi","infl.empty":"Không có influencer phù hợp.",
    "svc.title":"Dịch vụ","svc.sub":"Lan tỏa bằng nội dung, bán bằng thương mại, hợp pháp bằng chứng nhận.",
    "svc.a.t":"Live & V-Commerce","svc.a.d":"Phiên bán hàng trực tiếp do streamer hàng đầu dẫn dắt, tạo chuyển đổi tức thì.","svc.a.1":"Live commerce TikTok & Facebook","svc.a.2":"Deal & khuyến mãi trực tiếp","svc.a.3":"Dữ liệu & báo cáo bán hàng",
    "svc.b.t":"Mua chung & Vận hành mall","svc.b.d":"Mua chung dựa trên fandom và vận hành mall bản địa tạo doanh thu bền vững.","svc.b.1":"Lên kế hoạch mua chung","svc.b.2":"Niêm yết & vận hành TMĐT","svc.b.3":"CSKH, logistics & quyết toán",
    "svc.c.t":"Pop-up & Offline","svc.c.d":"Chiến lược O2O với pop-up trải nghiệm và sự kiện, xây niềm tin và độ nhận biết.","svc.c.1":"Lên kế hoạch & vận hành pop-up","svc.c.2":"Sự kiện ra mắt có người nổi tiếng","svc.c.3":"Sự kiện chính phủ & doanh nghiệp",
    "svc.d.t":"Nội dung & Chiến dịch","svc.d.d":"Nội dung chất lượng cao không giống quảng cáo, lồng ghép thương hiệu tự nhiên.","svc.d.1":"PPL web-drama & MV","svc.d.2":"Chiến dịch short-form & MXH","svc.d.3":"PR báo chí & ảnh tạp chí",
    "svc.e.t":"Chứng nhận Việt Nam","svc.e.d":"Pháp nhân Việt Nam của chúng tôi tự công bố mỹ phẩm (DAV) và đăng ký thực phẩm (VFA) để bán hợp pháp.","svc.e.1":"Công bố mỹ phẩm — DAV","svc.e.2":"Đăng ký an toàn thực phẩm — VFA","svc.e.3":"Nhập khẩu, hải quan & nhãn mác",
    "svc.f.t":"Tìm nguồn thương hiệu (Hàn)","svc.f.d":"Brooks Global, chi nhánh Hàn Quốc, phụ trách tìm nguồn thương hiệu và liên lạc.","svc.f.1":"Tìm nguồn & hợp đồng","svc.f.2":"Lên kế hoạch & quản lý chiến dịch","svc.f.3":"Báo cáo & quyết toán",
    "about.title":"Giới thiệu","about.sub":"Công ty marketing số kết nối năng lượng ASEAN với Hàn Quốc.",
    "about.story.t":"WE MAKE COOL STUFF FOR YOUR BRAND","about.story.d":"Đặt trụ sở tại TP.HCM, Young Wave Creative đã dẫn dắt nhiều dự án khắp ASEAN. Lấy hợp tác với người nổi tiếng và influencer hàng đầu khu vực làm trọng tâm, chúng tôi quảng bá thành công văn hóa, sản phẩm và du lịch Hàn Quốc. Từ nội dung đến V-commerce và bán hàng bản địa — chúng tôi là cầu nối mạnh mẽ giữa ASEAN và Hàn Quốc.",
    "about.fact.name":"Công ty","about.fact.ceo":"CEO","about.fact.found":"Thành lập","about.fact.hq":"Trụ sở","about.fact.team":"Nhân sự","about.fact.biz":"Lĩnh vực",
    "about.found.v":"Thành lập tại TP.HCM, 2016","about.team.v":"16 tại VN · 3 tại Hàn Quốc","about.biz.v":"Nội dung · MCN/influencer · quảng cáo · V-commerce · marketing ASEAN",
    "about.tl.title":"Dự án tiêu biểu","about.ceo.title":"Lãnh đạo","ceo.role":"CEO / Giám đốc Kế hoạch, Văn phòng Du lịch Quốc gia Việt Nam tại Hàn Quốc",
    "ceo.c1":"Đại sứ Du lịch Việt Nam tại Hàn (2017–2029)","ceo.c2":"Huân chương 'Đại đoàn kết dân tộc' MTTQ Việt Nam","ceo.c3":"Bằng khen của Bộ trưởng VHTTDL Hàn Quốc","ceo.c4":"Tổng đạo diễn nhiều sự kiện chính phủ & doanh nghiệp Hàn tại Việt Nam",
    "about.rel.title":"Mạng lưới liên kết",
    "contact.title":"Liên hệ hợp tác","contact.sub":"Để lại thông tin thương hiệu, chúng tôi gửi đề xuất trong 2 ngày làm việc.",
    "f.name":"Họ tên","f.company":"Công ty / thương hiệu","f.email":"Email","f.cat":"Danh mục sản phẩm","f.country":"Quốc gia mục tiêu","f.msg":"Nội dung","f.send":"Gửi liên hệ",
    "f.cat.ph":"Chọn","f.cat.cosmetic":"Mỹ phẩm","f.cat.food":"Thực phẩm","f.cat.living":"Hàng gia dụng","f.cat.game":"Game di động","f.cat.device":"Điện tử","f.cat.etc":"Khác",
    "f.note":"Khi gửi, ứng dụng email sẽ mở với nội dung điền sẵn.",
    "contact.office":"Văn phòng Việt Nam","contact.kr":"Hàn Quốc (Brooks Global)","contact.email":"Email",
    "foot.tag":"Đối tác influencer-commerce kết nối Hàn Quốc, Đông Nam Á & châu Âu.","foot.menu":"Menu","foot.contact":"Liên hệ","foot.partner":"Đối tác chi nhánh Hàn","foot.rights":"Bảo lưu mọi quyền."
  },
  th:{
    "nav.home":"หน้าแรก","nav.influencers":"อินฟลูเอนเซอร์","nav.services":"บริการ","nav.about":"เกี่ยวกับเรา","nav.contact":"ติดต่อ",
    "cta.brand":"ติดต่อแบรนด์","cta.explore":"ดูรายชื่อ",
    "hero.badge":"การตลาดอินฟลูเอนเซอร์ เกาหลี × เอเชียตะวันออกเฉียงใต้",
    "hero.title1":"อินฟลูเอนเซอร์คอมเมิร์ซยุโรป·อาเซียน","hero.title2":"บริษัทฟูลสแตก",
    "hero.lead":"เราไม่ได้ขายโฆษณา ด้วยเซเลบ + พูลอินฟลูเอนเซอร์ เราสร้างยอดขายในเอเชียตะวันออกเฉียงใต้และยุโรปให้แบรนด์ ขั้นตอนการขายข้ามพรมแดนที่ซับซ้อนถูกรวมเป็นไปป์ไลน์เดียว — ง่าย ไปจนถึงยอดขาย",
    "marquee":"อินฟลูเอนเซอร์ → คอนเทนต์ → ไลฟ์คอมเมิร์ซ → ขายร้านค้า → กระทบยอด · ใบรับรองเครื่องสำอาง (DAV·VFA) · ศุลกากร & 3PL · ป๊อปอัพ",
    "stats.title":"Young Wave ในตัวเลข","stats.sub":"เครือข่ายจริงที่ครอบคลุมทั้งภูมิภาค",
    "stat.reach":"การเข้าถึงรวม","stat.countries":"ประเทศอาเซียน","stat.years":"ปีดำเนินงานในเวียดนาม","stat.team":"ทีมในเวียดนามและเกาหลี",
    "home.svc.title":"พาร์ทเนอร์เดียว ครบวงจร","home.svc.sub":"ตั้งแต่หาโฆษณาจนถึงปิดการขายในพื้นที่ — ครบจบ",
    "home.why.title":"ทำไมต้องอาเซียนและยุโรป ทำไมต้องตอนนี้","home.why.sub":"60% ของประชากรเวียดนาม 100 ล้านคนอายุต่ำกว่า 35 และชื่นชอบวัฒนธรรมเกาหลี",
    "why.1.t":"ตลาดผู้บริโภควัยหนุ่มสาว","why.1.d":"60% ของประชากรเวียดนามอายุต่ำกว่า 35 ตลาดที่เติบโตเร็วด้านมือถือและอีคอมเมิร์ซ",
    "why.2.t":"พรีเมียมฮัลลยู","why.2.d":"ภาพลักษณ์ที่ดีของวัฒนธรรมเกาหลีครองใจผู้บริโภครุ่นใหม่",
    "why.3.t":"ศักยภาพในพื้นที่","why.3.d":"ประสบการณ์ตั้งแต่งานภาครัฐ องค์กร จนถึงเว็บดราม่าเกาหลี-เวียดนาม",
    "home.infl.title":"ครีเอเตอร์พร้อมร่วมงาน","home.infl.sub":"ส่วนหนึ่งของพูลที่คัดสรรตามหมวดและประเทศ",
    "home.partner.title":"บริษัทในเครือ & พันธมิตร","home.partner.sub":"ตั้งแต่ MCN ใหญ่สุดในเวียดนามจนถึงลิขสิทธิ์ Miss Universe",
    "partners.metub":"MCN ใหญ่สุดในเวียดนาม","partners.uni":"Miss Universe Vietnam","partners.choo":"การตลาด & อีเวนต์","partners.zorba":"โปรดักชันรางวัลคานส์",
    "cta.title":"เริ่มเข้าสู่เอเชียตะวันออกเฉียงใต้และยุโรปวันนี้","cta.sub":"บอกเราเกี่ยวกับแบรนด์ของคุณ เราจะเสนอกลยุทธ์ที่เหมาะสม","cta.btn":"ขอคำปรึกษา",
    "infl.title":"พูลอินฟลูเอนเซอร์","infl.sub":"คนดังและครีเอเตอร์ที่คัดสรรในเวียดนาม ฟิลิปปินส์ และไทย กรองตามประเทศและหมวด",
    "filter.all":"ทั้งหมด","infl.count":"คน","followers":"ผู้ติดตาม","infl.empty":"ไม่พบอินฟลูเอนเซอร์ที่ตรงเงื่อนไข",
    "svc.title":"บริการ","svc.sub":"เข้าถึงด้วยคอนเทนต์ ขายด้วยคอมเมิร์ซ ถูกกฎหมายด้วยใบรับรอง",
    "svc.a.t":"ไลฟ์ & V-Commerce","svc.a.d":"ไลฟ์ขายสดโดยสตรีมเมอร์ระดับท็อป สร้างการเปลี่ยนแปลงทันที","svc.a.1":"ไลฟ์คอมเมิร์ซ TikTok & Facebook","svc.a.2":"ดีล & โปรโมชันสด","svc.a.3":"ข้อมูล & รายงานการขาย",
    "svc.b.t":"ซื้อร่วม & บริหารร้าน","svc.b.d":"ซื้อร่วมจากแฟนคลับและบริหารร้านในพื้นที่ สร้างรายได้ต่อเนื่อง","svc.b.1":"วางแผนซื้อร่วม","svc.b.2":"ลงขาย & บริหารอีคอมเมิร์ซ","svc.b.3":"CS โลจิสติกส์ & การชำระเงิน",
    "svc.c.t":"ป๊อปอัพ & ออฟไลน์","svc.c.d":"กลยุทธ์ O2O ด้วยป๊อปอัพเชิงประสบการณ์และอีเวนต์ สร้างความเชื่อมั่นและการรับรู้","svc.c.1":"วางแผน & บริหารป๊อปอัพ","svc.c.2":"อีเวนต์เปิดตัวกับคนดัง","svc.c.3":"อีเวนต์ภาครัฐ & องค์กร",
    "svc.d.t":"คอนเทนต์ & แคมเปญ","svc.d.d":"คอนเทนต์คุณภาพสูงที่ไม่เหมือนโฆษณา สอดแทรกแบรนด์อย่างเป็นธรรมชาติ","svc.d.1":"PPL เว็บดราม่า & MV","svc.d.2":"แคมเปญ short-form & โซเชียล","svc.d.3":"PR สื่อ & ภาพนิตยสาร",
    "svc.e.t":"ใบรับรองเวียดนาม","svc.e.d":"นิติบุคคลเวียดนามของเราดำเนินการแจ้งเครื่องสำอาง (DAV) และจดทะเบียนอาหาร (VFA) เพื่อการขายถูกกฎหมาย","svc.e.1":"แจ้งเครื่องสำอาง — DAV","svc.e.2":"จดทะเบียนความปลอดภัยอาหาร — VFA","svc.e.3":"นำเข้า ศุลกากร & ฉลาก",
    "svc.f.t":"จัดหาแบรนด์ (เกาหลี)","svc.f.d":"Brooks Global สาขาเกาหลีของเรา ดูแลการจัดหาแบรนด์และการสื่อสาร","svc.f.1":"จัดหา & ทำสัญญาแบรนด์","svc.f.2":"วางแผน & บริหารแคมเปญ","svc.f.3":"รายงาน & การชำระเงิน",
    "about.title":"เกี่ยวกับเรา","about.sub":"บริษัทการตลาดดิจิทัลที่เชื่อมพลังอาเซียนกับเกาหลี",
    "about.story.t":"WE MAKE COOL STUFF FOR YOUR BRAND","about.story.d":"Young Wave Creative มีฐานที่โฮจิมินห์ และนำโครงการต่าง ๆ ทั่วอาเซียน ด้วยความร่วมมือกับคนดังและอินฟลูเอนเซอร์ชั้นนำของภูมิภาค เราโปรโมตวัฒนธรรม สินค้า และการท่องเที่ยวเกาหลีได้สำเร็จ ตั้งแต่คอนเทนต์ถึง V-commerce และการขายในพื้นที่ เราคือสะพานที่แข็งแกร่งระหว่างอาเซียนและเกาหลี",
    "about.fact.name":"บริษัท","about.fact.ceo":"CEO","about.fact.found":"ก่อตั้ง","about.fact.hq":"สำนักงานใหญ่","about.fact.team":"ทีม","about.fact.biz":"ธุรกิจ",
    "about.found.v":"ก่อตั้งที่โฮจิมินห์ 2016","about.team.v":"16 คนในเวียดนาม · 3 คนในเกาหลี","about.biz.v":"คอนเทนต์ · MCN/อินฟลูเอนเซอร์ · โฆษณา · V-commerce · การตลาดอาเซียน",
    "about.tl.title":"โครงการเด่น","about.ceo.title":"ผู้นำ","ceo.role":"CEO / ผู้อำนวยการฝ่ายแผน สำนักงานการท่องเที่ยวแห่งชาติเวียดนามในเกาหลี",
    "ceo.c1":"ทูตการท่องเที่ยวเวียดนามประจำเกาหลี (2017–2029)","ceo.c2":"เหรียญ 'สามัคคีชาติ' แนวร่วมปิตุภูมิเวียดนาม","ceo.c3":"เกียรติบัตรจากรัฐมนตรีวัฒนธรรมฯ เกาหลี","ceo.c4":"กำกับงานภาครัฐ & องค์กรเกาหลีหลายงานในเวียดนาม",
    "about.rel.title":"เครือข่ายบริษัทในเครือ",
    "contact.title":"ติดต่อความร่วมมือ","contact.sub":"ฝากข้อมูลแบรนด์ เราจะส่งข้อเสนอภายใน 2 วันทำการ",
    "f.name":"ชื่อ","f.company":"บริษัท / แบรนด์","f.email":"อีเมล","f.cat":"หมวดสินค้า","f.country":"ประเทศเป้าหมาย","f.msg":"ข้อความ","f.send":"ส่งข้อความ",
    "f.cat.ph":"เลือก","f.cat.cosmetic":"เครื่องสำอาง","f.cat.food":"อาหาร","f.cat.living":"ของใช้ในบ้าน","f.cat.game":"เกมมือถือ","f.cat.device":"อิเล็กทรอนิกส์","f.cat.etc":"อื่น ๆ",
    "f.note":"เมื่อส่ง แอปอีเมลจะเปิดพร้อมข้อความที่กรอกไว้",
    "contact.office":"สำนักงานเวียดนาม","contact.kr":"เกาหลี (Brooks Global)","contact.email":"อีเมล",
    "foot.tag":"พาร์ทเนอร์อินฟลูเอนเซอร์คอมเมิร์ซที่เชื่อมเกาหลี เอเชียตะวันออกเฉียงใต้ และยุโรป","foot.menu":"เมนู","foot.contact":"ติดต่อ","foot.partner":"พาร์ทเนอร์สาขาเกาหลี","foot.rights":"สงวนลิขสิทธิ์"
  },
  id:{
    "nav.home":"Beranda","nav.influencers":"Influencer","nav.services":"Layanan","nav.about":"Tentang","nav.contact":"Kontak",
    "cta.brand":"Kerja Sama Brand","cta.explore":"Lihat Daftar",
    "hero.badge":"Marketing Influencer Korea × Asia Tenggara",
    "hero.title1":"Influencer-Commerce Eropa · Asia Tenggara","hero.title2":"Perusahaan Full-Stack",
    "hero.lead":"Kami tidak menjual iklan. Dengan selebriti + kumpulan influencer, kami menciptakan penjualan Asia Tenggara & Eropa untuk brand. Langkah penjualan lintas batas yang rumit disatukan dalam satu pipeline — mudah, hingga ke penjualan.",
    "marquee":"Influencer → Konten → Live Commerce → Penjualan Mall → Penyelesaian · Sertifikasi Kosmetik (DAV·VFA) · Bea Cukai & 3PL · Pop-up",
    "stats.title":"Young Wave dalam angka","stats.sub":"Jaringan teruji yang mencakup kawasan",
    "stat.reach":"Total jangkauan influencer","stat.countries":"Negara ASEAN","stat.years":"Tahun beroperasi di Vietnam","stat.team":"Tim di Vietnam & Korea",
    "home.svc.title":"Satu partner, tuntas","home.svc.sub":"Dari mencari iklan hingga menutup penjualan lokal — full-stack.",
    "home.why.title":"Mengapa Asia Tenggara & Eropa, mengapa sekarang","home.why.sub":"60% dari 100 juta penduduk Vietnam berusia di bawah 35 dan menyukai budaya Korea.",
    "why.1.t":"Pasar konsumen muda","why.1.d":"60% populasi Vietnam di bawah 35 — pasar berkembang dengan pertumbuhan mobile dan e-commerce yang pesat.",
    "why.2.t":"Premium Hallyu","why.2.d":"Citra positif budaya Korea mendominasi konsumen muda, memudahkan masuknya brand Korea.",
    "why.3.t":"Eksekusi lokal teruji","why.3.d":"Rekam jejak menangani acara pemerintah, korporat, hingga web drama Korea–Vietnam.",
    "home.infl.title":"Kreator siap berkolaborasi","home.infl.sub":"Sebagian dari pool yang dikurasi per kategori dan negara.",
    "home.partner.title":"Afiliasi & jaringan partner","home.partner.sub":"Dari MCN terbesar Vietnam hingga lisensi Miss Universe.",
    "partners.metub":"MCN terbesar Vietnam","partners.uni":"Miss Universe Vietnam","partners.choo":"Marketing & acara","partners.zorba":"Produksi peraih Cannes",
    "cta.title":"Mulai ekspansi Asia Tenggara & Eropa sekarang","cta.sub":"Ceritakan brand Anda dan kami usulkan strategi yang tepat.","cta.btn":"Minta konsultasi",
    "infl.title":"Pool Influencer","infl.sub":"Selebriti dan kreator terverifikasi di Vietnam, Filipina, dan Thailand. Saring per negara dan kategori.",
    "filter.all":"Semua","infl.count":"influencer","followers":"pengikut","infl.empty":"Tidak ada influencer yang cocok.",
    "svc.title":"Layanan","svc.sub":"Jangkau dengan konten, jual dengan commerce, legalkan dengan sertifikasi.",
    "svc.a.t":"Live & V-Commerce","svc.a.d":"Siaran jual langsung oleh streamer top yang mendorong konversi instan.","svc.a.1":"Live commerce TikTok & Facebook","svc.a.2":"Deal & promo langsung","svc.a.3":"Data & laporan penjualan",
    "svc.b.t":"Group Buy & Operasi Toko","svc.b.d":"Group buy berbasis fandom dan operasi toko lokal untuk pendapatan berkelanjutan.","svc.b.1":"Perencanaan group buy","svc.b.2":"Listing & operasi e-commerce","svc.b.3":"CS, logistik & penyelesaian",
    "svc.c.t":"Pop-up & Offline","svc.c.d":"Strategi O2O dengan pop-up pengalaman dan acara untuk membangun kepercayaan dan kesadaran.","svc.c.1":"Perencanaan & operasi pop-up","svc.c.2":"Acara peluncuran dengan selebriti","svc.c.3":"Acara pemerintah & korporat",
    "svc.d.t":"Konten & Kampanye","svc.d.d":"Konten berkualitas tinggi yang tak terasa seperti iklan, menyisipkan brand secara alami.","svc.d.1":"PPL web-drama & MV","svc.d.2":"Kampanye short-form & sosial","svc.d.3":"PR pers & foto majalah",
    "svc.e.t":"Sertifikasi Vietnam","svc.e.d":"Entitas Vietnam kami mengurus notifikasi kosmetik (DAV) dan registrasi makanan (VFA) untuk penjualan legal.","svc.e.1":"Notifikasi kosmetik — DAV","svc.e.2":"Registrasi keamanan pangan — VFA","svc.e.3":"Impor, bea cukai & label",
    "svc.f.t":"Sourcing Brand (Korea)","svc.f.d":"Brooks Global, cabang Korea kami, memimpin sourcing brand dan komunikasi.","svc.f.1":"Sourcing & kontrak brand","svc.f.2":"Perencanaan & manajemen kampanye","svc.f.3":"Pelaporan & penyelesaian",
    "about.title":"Tentang Kami","about.sub":"Perusahaan marketing digital yang menghubungkan energi ASEAN dengan Korea.",
    "about.story.t":"WE MAKE COOL STUFF FOR YOUR BRAND","about.story.d":"Berbasis di Ho Chi Minh City, Young Wave Creative telah memimpin proyek di seluruh ASEAN. Berpusat pada kolaborasi dengan selebriti dan influencer top kawasan, kami berhasil mempromosikan budaya, produk, dan pariwisata Korea. Dari konten hingga V-commerce dan penjualan lokal — kami menjadi jembatan kuat antara ASEAN dan Korea.",
    "about.fact.name":"Perusahaan","about.fact.ceo":"CEO","about.fact.found":"Berdiri","about.fact.hq":"Kantor pusat","about.fact.team":"Tim","about.fact.biz":"Bisnis",
    "about.found.v":"Berdiri di Ho Chi Minh City, 2016","about.team.v":"16 di Vietnam · 3 di Korea","about.biz.v":"Konten · MCN/influencer · iklan · V-commerce · marketing ASEAN",
    "about.tl.title":"Proyek Unggulan","about.ceo.title":"Kepemimpinan","ceo.role":"CEO / Direktur Perencanaan, Kantor Pariwisata Nasional Vietnam di Korea",
    "ceo.c1":"Duta Pariwisata Vietnam untuk Korea (2017–2029)","ceo.c2":"Medali 'Persatuan Besar' Front Tanah Air Vietnam","ceo.c3":"Penghargaan dari Menteri Kebudayaan Korea","ceo.c4":"Mengarahkan banyak acara pemerintah & korporat Korea di Vietnam",
    "about.rel.title":"Jaringan Afiliasi",
    "contact.title":"Pertanyaan Kemitraan","contact.sub":"Tinggalkan detail brand Anda, kami kirim proposal dalam 2 hari kerja.",
    "f.name":"Nama","f.company":"Perusahaan / brand","f.email":"Email","f.cat":"Kategori produk","f.country":"Negara target","f.msg":"Pesan","f.send":"Kirim",
    "f.cat.ph":"Pilih","f.cat.cosmetic":"Kosmetik","f.cat.food":"Makanan","f.cat.living":"Kebutuhan rumah","f.cat.game":"Game mobile","f.cat.device":"Elektronik","f.cat.etc":"Lainnya",
    "f.note":"Saat dikirim, aplikasi email akan terbuka dengan pesan terisi.",
    "contact.office":"Kantor Vietnam","contact.kr":"Korea (Brooks Global)","contact.email":"Email",
    "foot.tag":"Partner influencer-commerce yang menghubungkan Korea, Asia Tenggara & Eropa.","foot.menu":"Menu","foot.contact":"Kontak","foot.partner":"Partner Cabang Korea","foot.rights":"Hak cipta dilindungi."
  },
  zh:{
    "nav.home":"首页","nav.influencers":"网红资源","nav.services":"服务","nav.about":"关于我们","nav.contact":"联系我们",
    "cta.brand":"品牌合作咨询","cta.explore":"查看资源库",
    "hero.badge":"韩国 × 东南亚 网红营销",
    "hero.title1":"欧洲·东南亚网红电商","hero.title2":"全栈公司",
    "hero.lead":"我们不卖广告。凭借明星 + 网红资源库，我们为品牌创造东南亚与欧洲销售额。把原本分散管理的复杂跨境销售环节，整合为一条流水线——轻松，直达营收。",
    "marquee":"网红 → 内容制作 → 直播电商 → 商城销售 → 结算 · 化妆品认证(DAV·VFA) · 通关 & 3PL · 本地快闪",
    "stats.title":"数字里的 Young Wave","stats.sub":"覆盖全区域的实战网络",
    "stat.reach":"网红累计触达","stat.countries":"覆盖东盟国家","stat.years":"越南本地运营年数","stat.team":"越南与韩国团队",
    "home.svc.title":"一个伙伴，全程到底","home.svc.sub":"从广告对接到本地销售成交——全栈执行。",
    "home.why.title":"为何东南亚与欧洲，为何此刻","home.why.sub":"越南一亿人口中 60% 在 35 岁以下，且高度认同韩流文化。",
    "why.1.t":"年轻的消费市场","why.1.d":"越南 60% 人口在 35 岁以下——移动与电商高速增长的崛起市场。",
    "why.2.t":"韩流溢价","why.2.d":"对韩流文化的好感在年轻消费群体中占主导，利于韩国品牌进入。",
    "why.3.t":"经验证的本地执行力","why.3.d":"从政府、大企业活动到韩越网络剧，均有亲自落地运营的实绩。",
    "home.infl.title":"可立即合作的创作者","home.infl.sub":"按品类与国家精选资源库的一部分。",
    "home.partner.title":"关联公司与合作网络","home.partner.sub":"从越南最大 MCN 到环球小姐授权。",
    "partners.metub":"越南最大 MCN","partners.uni":"越南环球小姐","partners.choo":"整合营销与活动","partners.zorba":"戛纳获奖制作公司",
    "cta.title":"立即开启东南亚与欧洲布局","cta.sub":"告诉我们您的品牌，我们将提出最合适的网红与渠道策略。","cta.btn":"申请咨询",
    "infl.title":"网红资源库","infl.sub":"越南、菲律宾、泰国经过甄选的明星与创作者。可按国家与品类筛选。",
    "filter.all":"全部","infl.count":"位网红","followers":"粉丝","infl.empty":"没有符合条件的网红。",
    "svc.title":"服务","svc.sub":"用内容触达，用电商销售，用认证合规。",
    "svc.a.t":"直播 & V-Commerce","svc.a.d":"由顶级主播主持的实时销售直播，带来即时转化。","svc.a.1":"TikTok & Facebook 直播电商","svc.a.2":"网红实时优惠与促销","svc.a.3":"销售数据与报告",
    "svc.b.t":"团购 & 商城运营","svc.b.d":"基于粉丝的团购与本地商城运营，创造持续营收。","svc.b.1":"网红团购策划","svc.b.2":"本地电商上架与运营","svc.b.3":"客服、物流与结算",
    "svc.c.t":"本地快闪 & 线下","svc.c.d":"以 O2O 策略，通过体验式快闪与活动同时建立信任与认知。","svc.c.1":"本地快闪店策划运营","svc.c.2":"明星出席发布活动","svc.c.3":"政府与大企业活动",
    "svc.d.t":"内容 & 战役","svc.d.d":"不像广告的高品质内容，将品牌自然融入，提升认知。","svc.d.1":"网络剧与 MV 植入","svc.d.2":"短视频与社媒战役","svc.d.3":"媒体公关与杂志大片",
    "svc.e.t":"越南认证（化妆品·食品）","svc.e.d":"我们的越南法人直接办理化妆品申报（DAV）与食品注册（VFA），保障合法销售。","svc.e.1":"化妆品申报 — 卫生部 DAV","svc.e.2":"食品安全注册 — VFA","svc.e.3":"进口、清关与标签",
    "svc.f.t":"品牌对接（韩国分公司）","svc.f.d":"Brooks Global 作为韩国分公司，专责品牌/广告主对接与沟通。","svc.f.1":"韩国品牌对接与签约","svc.f.2":"战役策划与管理","svc.f.3":"报告与结算沟通",
    "about.title":"关于我们","about.sub":"连接东盟活力与韩国的数字整合营销公司。",
    "about.story.t":"WE MAKE COOL STUFF FOR YOUR BRAND","about.story.d":"Young Wave Creative 以胡志明市为据点，主导了遍及东盟的项目。以与区域顶级明星和网红的合作为核心，成功推广韩国文化、产品与旅游。从内容到 V-commerce 再到本地销售——我们立志成为连接东盟与韩国的坚实桥梁。",
    "about.fact.name":"公司名","about.fact.ceo":"代表","about.fact.found":"成立","about.fact.hq":"总部","about.fact.team":"团队","about.fact.biz":"主营业务",
    "about.found.v":"2016 年胡志明市成立","about.team.v":"越南总部 16 人 · 韩国分公司 3 人","about.biz.v":"内容制作 · MCN/网红营销 · 广告代理 · V-commerce · 东盟整合营销",
    "about.tl.title":"代表项目","about.ceo.title":"领导团队","ceo.role":"代表 / 越南国家旅游局驻韩代表处企划局长",
    "ceo.c1":"越南驻韩旅游大使（2017–2029）","ceo.c2":"越南祖国阵线'民族大团结'勋章","ceo.c3":"韩国文化体育观光部长官表彰","ceo.c4":"在越南统筹多项韩国政府与大企业活动",
    "about.rel.title":"关联网络",
    "contact.title":"合作咨询","contact.sub":"留下品牌信息，我们将在 2 个工作日内发送定制方案。",
    "f.name":"联系人","f.company":"公司 / 品牌","f.email":"邮箱","f.cat":"产品类别","f.country":"目标国家","f.msg":"咨询内容","f.send":"提交咨询",
    "f.cat.ph":"请选择","f.cat.cosmetic":"化妆品","f.cat.food":"食品","f.cat.living":"生活用品","f.cat.game":"手机游戏","f.cat.device":"电子产品","f.cat.etc":"其他",
    "f.note":"提交时将打开邮件客户端并预填内容。",
    "contact.office":"越南办公室","contact.kr":"韩国（Brooks Global）","contact.email":"邮箱",
    "foot.tag":"连接韩国、东南亚与欧洲的网红电商伙伴。","foot.menu":"菜单","foot.contact":"联系","foot.partner":"韩国分公司伙伴","foot.rights":"版权所有。"
  }
};

const LANGS = [
  {code:"ko",label:"한국어"},{code:"en",label:"English"},{code:"vi",label:"Tiếng Việt"},
  {code:"th",label:"ไทย"},{code:"id",label:"Indonesia"},{code:"zh",label:"中文"}
];
